# Generated by Django 4.0.1 on 2022-01-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Meat', 'Meat'), ('Spice', 'Spice'), ('Dairy', 'Dairy'), ('Bread', 'Bread'), ('Other', 'Other')], max_length=20)),
                ('kcal_unit', models.CharField(choices=[('100', 'kcal/100g'), ('10', 'kcal/10g'), ('1', 'kcal/1g')], max_length=20)),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.ManyToManyField(to='recipes.Product')),
            ],
        ),
    ]
